customhost = "employee.cdu1nmpdtkqc.us-east-1.rds.amazonaws.com"
customuser = "adminmohammed"
custompass = "1q2w3e4r5t"
customdb = "employee"
custombucket = "addemployees11"
customregion = "us-east-1"
